# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x06search\"J\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\t\x12\r\n\x05top_k\x18\x03 \x01(\x05\x12\r\n\x05\x61lpha\x18\x04 \x01(\x02\"q\n\x0bPaperResult\x12\x0c\n\x04rank\x18\x01 \x01(\x05\x12\r\n\x05paper\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\x12\x15\n\rquality_score\x18\x04 \x01(\x02\x12\x0e\n\x06rubric\x18\x05 \x01(\x02\x12\x0f\n\x07\x63omment\x18\x06 \x01(\t\"b\n\x0eSearchResponse\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\t\x12$\n\x07results\x18\x03 \x03(\x0b\x32\x13.search.PaperResult\x12\r\n\x05\x63\x61\x63he\x18\x04 \x01(\t\"0\n\x10RecommendRequest\x12\r\n\x05paper\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"P\n\x11RecommendResponse\x12\r\n\x05paper\x18\x01 \x01(\t\x12,\n\x0frecommendations\x18\x02 \x03(\x0b\x32\x13.search.PaperResult2\x8a\x01\n\rSearchService\x12\x37\n\x06Search\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponse\x12@\n\tRecommend\x12\x18.search.RecommendRequest\x1a\x19.search.RecommendResponseB\x14Z\x12papergateway/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022papergateway/proto'
  _globals['_SEARCHREQUEST']._serialized_start=24
  _globals['_SEARCHREQUEST']._serialized_end=98
  _globals['_PAPERRESULT']._serialized_start=100
  _globals['_PAPERRESULT']._serialized_end=213
  _globals['_SEARCHRESPONSE']._serialized_start=215
  _globals['_SEARCHRESPONSE']._serialized_end=313
  _globals['_RECOMMENDREQUEST']._serialized_start=315
  _globals['_RECOMMENDREQUEST']._serialized_end=363
  _globals['_RECOMMENDRESPONSE']._serialized_start=365
  _globals['_RECOMMENDRESPONSE']._serialized_end=445
  _globals['_SEARCHSERVICE']._serialized_start=448
  _globals['_SEARCHSERVICE']._serialized_end=586
# @@protoc_insertion_point(module_scope)
